source 'http://rubygems.org'

gem "mongo"
gem "bson_ext"
#gem "mongo_mapper"
gem 'mongo_mapper', :git => "git://github.com/mongomapper/mongomapper.git", :tag => "v0.13.0.beta2"
gem "json"
gem "zip"
gem "nokogiri"
gem "readline-history-restore"
gem "spidr"
gem "geokit"
gem "sinatra"
gem "rest-client"
gem "pdf-reader"
gem "pdfkit"
gem "awesome_print"
gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"
